services:
  - type: web
    name: av-academy-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://av-academy-3cf7.vercel.app,https://www.avacademy.lk,https://avacademy.lk,http://localhost:5173
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
